parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
env:
  browser: true
  es6: true
rules:
  no-multi-spaces:
    - error
  key-spacing:
    - error
  space-infix-ops:
    - error
  space-in-parens:
    - error
  space-before-function-paren:
    - error
    - never
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  no-undef: off
  no-console:
    - error
  "@typescript-eslint/camelcase":
    - error
    -
      properties: always
  no-multiple-empty-lines:
    - error
    -
      max: 1
      maxEOF: 0
  "@typescript-eslint/explicit-member-accessibility":
    - error
    -
      ignoredMethodNames:
        - "constructor"
        - "render"
        - "componentDidMount"
        - "componentDidUpdate"
        - "componentWillUnmount"
  "@typescript-eslint/member-delimiter-style":
    - error
    -
      singleline:
        delimiter: comma
  "@typescript-eslint/class-name-casing":
    - error
  "@typescript-eslint/explicit-function-return-type":
    - error
  require-await:
    - error
  no-return-await:
    - error
  lines-between-class-members:
    - error
    - always
  padding-line-between-statements:
    - error
    -
      blankLine: always
      prev:
        - class
      next: "*"
  no-mixed-spaces-and-tabs:
    - error
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  object-curly-spacing:
    - error
    - always
  curly:
    - error
    - all
  eqeqeq:
    - error
  quotes:
    - error
    - single
  no-unused-vars: off
  semi: error
  no-dupe-class-members: off
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true
settings:
  import/resolver: "webpack"